'use client';
import { useState } from 'react';
import { ArrowDown, ArrowUpRight, Code2, Flame, Gamepad2, MessageSquare, Plus, Search, Sparkles } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { games, type Game } from '@/lib/games';
const categories=['All games','Arcade','Puzzle','Exploration','One-shot'];
export default function Home() {
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All games');
 const [selected,setSelected]=useState<Game|null>(null),[submitOpen,setSubmitOpen]=useState(false);
 const [feedback,setFeedback]=useState(''),[name,setName]=useState(''),[status,setStatus]=useState(''),[sending,setSending]=useState(false);
 const filtered=games.filter(g=>(category==='All games'||g.tags.includes(category))&&`${g.title} ${g.description} ${g.tags.join(' ')} ${g.model}`.toLowerCase().includes(query.toLowerCase()));
 function openGame(g:Game){setSelected(g);setStatus('');}
 async function sendFeedback(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||sending)return;setSending(true);setStatus('');try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gameId:selected.id,name,text:feedback})});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Could not send feedback. Please try again.');setStatus('Thanks! Your feedback was saved for review.');setFeedback('');}catch(error){setStatus(error instanceof Error?error.message:'Could not send feedback. Please try again.');}finally{setSending(false);}}
 return <div className="site-shell">
 <header className="topbar"><a className="brand" href="/" aria-label="SourceHearth home"><span className="brand-mark"><Flame size={25} fill="currentColor"/></span>Source<span>Hearth</span><span className="alpha">EARLY ACCESS</span></a><nav aria-label="Main navigation"><a className="nav-active" href="#discover">Discover</a><button onClick={()=>setSubmitOpen(true)}>For creators <ArrowUpRight size={14}/></button></nav><button className="primary-button" onClick={()=>setSubmitOpen(true)}><Plus size={17}/> Submit a game</button></header>
 <main id="discover"><div className="intro-row"><div><p className="eyebrow"><span/> THE COMMUNITY ARCADE</p><h1>Small games. <span>Big imagination.</span></h1><p className="intro-copy">Discover free games made with AI. Play something new. See how it was built.</p></div><div className="free-note"><Gamepad2 size={22}/><span>Always free to play.<br/><strong>Always something to explore.</strong></span></div></div>
 <div className="preview-note"><Sparkles size={16}/><span>Preview collection · These three concepts show how your games will appear. Play and source links will arrive with real submissions.</span></div>
 <section className="feature" aria-labelledby="feature-title"><div className="feature-art"><img src="/images/orbit.png" alt="Concept artwork of a small orange astronaut exploring a blue alien world"/><span className="image-label">CONCEPT ART · SAMPLE LISTING</span></div><div className="feature-copy"><p className="eyebrow orange">A LITTLE WORLD TO GET LOST IN</p><div className="tag-row"><span>Exploration</span><span>3D</span></div><h2 id="feature-title">A little farther<br/>from home.</h2><p>Meet <strong>Little Orbit</strong>—a sample of the small, strange worlds that belong here. One curious explorer. An entire planet of possibilities.</p><button className="primary-button" onClick={()=>openGame(games[0])}>Explore the listing <ArrowUpRight size={17}/></button><span className="feature-footnote">Made with curiosity. Shared with everyone.</span></div></section>
 <section className="catalogue" aria-labelledby="catalogue-title"><div className="catalogue-heading"><h2 id="catalogue-title">Find your next little obsession<span>03</span></h2><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search games, genres…" aria-label="Search games"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search">×</button>}</label></div><Tabs value={category} onValueChange={v=>setCategory(String(v))}><div className="filter-row"><TabsList aria-label="Game category" className="category-tabs">{categories.map(t=><TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList><span className="sort-label">Newest first <ArrowDown size={14}/></span></div>{categories.map(t=><TabsContent key={t} value={t}><div className="games-grid">{filtered.map((game,index)=><article key={game.id} className="game-card"><button className={`card-cover ${game.art}`} onClick={()=>openGame(game)} aria-label={`View ${game.title}`}>{game.art==='orbit'?<img src="/images/orbit.png" alt="Little Orbit concept artwork"/>:<div className="type-cover"><span>{game.art==='tempo'?'JUST ONE':'THINK IN'}</span><strong>{game.art==='tempo'?'MORE.':'LOOPS'}</strong><span>{game.art==='tempo'?'A SMALL ARCADE OBSESSION':'A QUIET LITTLE PUZZLE'}</span></div>}<span className="sample-badge">Sample</span><span className="cover-arrow"><ArrowUpRight size={19}/></span></button><div className="card-body"><div className="card-title"><button onClick={()=>openGame(game)}>{game.title}</button><span>FREE</span></div><p>{game.description}</p><div className="card-meta"><span><Sparkles size={13}/>{game.model}</span><span>{game.tags[0]}</span></div><div className="card-bottom"><span>Concept listing <span className="muted">/ 0{index+1}</span></span><button onClick={()=>openGame(game)} aria-label={`Leave feedback on ${game.title}`}><MessageSquare size={15}/> Feedback</button></div></div></article>)}</div>{!filtered.length&&<div className="empty-state"><Search size={28}/><h3>No games found</h3><p>Try another search or explore all games.</p><button className="secondary-button" onClick={()=>{setQuery('');setCategory('All games');}}>Clear filters</button></div>}</TabsContent>)}</Tabs></section>
 <section className="creator-strip"><span className="creator-icon"><Code2 size={27}/></span><div><h2>Made a little something?</h2><p>Give your game a home in the collection. Keep hosting it wherever you like.</p></div><button className="secondary-button" onClick={()=>setSubmitOpen(true)}>Share your game <ArrowUpRight size={16}/></button></section></main>
 <footer><a className="brand small" href="/"><Flame size={18}/>SourceHearth</a><span>Free games. Open source. Human curiosity.</span><span className="footer-status"><span/> A community in the making</span></footer>
 <Dialog open={selected!==null} onOpenChange={open=>{if(!open&&!sending){setSelected(null);setFeedback('');setName('');setStatus('');}}}><DialogContent className="game-dialog sm:max-w-xl"><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.description}</DialogDescription>{selected&&<><div className="tag-row">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><div className="sample-explainer">This is a sample listing for the preview. No playable game or source repository is attached yet.</div><div className="dialog-actions">{selected.playUrl?<a className="primary-button" href={selected.playUrl} target="_blank" rel="noopener noreferrer">Play game <ArrowUpRight size={16}/></a>:<button className="primary-button" disabled>Play · Coming with real listings</button>}{selected.repoUrl&&<a className="secondary-button" href={selected.repoUrl} target="_blank" rel="noopener noreferrer">View source <Code2 size={16}/></a>}</div><form onSubmit={sendFeedback} className="feedback-form"><h3>Leave some feedback</h3><p>Feedback is saved privately for review. For sample listings, tell us what you think of the idea.</p><label>Your name <span>(optional)</span><input value={name} onChange={e=>setName(e.target.value)} maxLength={60} autoComplete="nickname" placeholder="Anonymous" disabled={sending}/></label><label>Your feedback<textarea value={feedback} onChange={e=>setFeedback(e.target.value)} required minLength={3} maxLength={2000} rows={4} placeholder="What caught your eye? What could be better?" disabled={sending}/></label><div className="form-bottom"><span>{feedback.length}/2000</span><button className="primary-button" disabled={sending||feedback.trim().length<3}>{sending?'Sending…':'Send feedback'} <ArrowUpRight size={15}/></button></div><p role="status" className="feedback-status">{status}</p></form></>}</DialogContent></Dialog>
 <Dialog open={submitOpen} onOpenChange={setSubmitOpen}><DialogContent className="game-dialog sm:max-w-lg"><DialogTitle>Bring your game to SourceHearth</DialogTitle><DialogDescription>Free to play. Public source. Made with a little help from AI.</DialogDescription><ol className="submission-steps"><li><strong>Host your game</strong><p>Keep it on your own site or a game hosting service.</p></li><li><strong>Share how it was made</strong><p>Include a screenshot, a short description, the model or tools you used, and links to play and source.</p></li><li><strong>Submit a listing for review</strong><p>Submissions will open through GitHub when the community repository is connected.</p></li></ol><div className="sample-explainer">The collection is being set up. Submissions aren’t open yet.</div></DialogContent></Dialog>
 </div>;
}

