'use client';
import { useState } from 'react';
import { ArrowDown, ArrowUpRight, Code2, Flame, MessageSquare, Plus, Search, Sparkles } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { games, type Game } from '@/lib/games';
import { GameChangelog } from '@/components/game-changelog';
const categories=['All games','Arcade','Survival','Mobile'];
export default function Home() {
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All games');
 const [selected,setSelected]=useState<Game|null>(null),[submitOpen,setSubmitOpen]=useState(false);
 const [feedback,setFeedback]=useState(''),[name,setName]=useState(''),[status,setStatus]=useState(''),[sending,setSending]=useState(false);
 const filtered=games.filter(g=>(category==='All games'||g.tags.includes(category))&&`${g.title} ${g.description} ${g.tags.join(' ')} ${g.model}`.toLowerCase().includes(query.toLowerCase()));
 function openGame(g:Game){setSelected(g);setStatus('');}
 async function sendFeedback(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||sending)return;setSending(true);setStatus('');try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gameId:selected.id,name,text:feedback})});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Could not send feedback. Please try again.');setStatus('Thanks! Your feedback was saved for review.');setFeedback('');}catch(error){setStatus(error instanceof Error?error.message:'Could not send feedback. Please try again.');}finally{setSending(false);}}
 return <div className="site-shell">
 <header className="topbar"><a className="brand" href="/" aria-label="SourceHearth home"><span className="brand-mark"><Flame size={25} fill="currentColor"/></span>Source<span>Hearth</span><span className="alpha">EARLY ACCESS</span></a><nav aria-label="Main navigation"><a className="nav-active" href="#discover">Discover</a><a href="https://github.com/blaksmatic/sourcehearth" target="_blank" rel="noopener noreferrer">GitHub ↗</a></nav><button className="primary-button" onClick={()=>setSubmitOpen(true)}><Plus size={17}/> Submit a game</button></header>
 <main id="discover"><div className="intro-row"><div><p className="eyebrow"><span/> THE COMMUNITY ARCADE</p><h1 className="sr-only">Discover games on SourceHearth</h1><p className="intro-copy">Discover free games made with AI. Play something new. See how it was built.</p></div></div>
 
 <section className="feature" aria-labelledby="feature-title"><div className="feature-art universe-art"><div className="universe-wordmark"><span>SURVIVE. EVOLVE. ASCEND.</span><strong>UNIVERSE<br/>EATER</strong><span>ASCENSION</span></div><span className="image-label">BY BLAKSMATIC · BROWSER GAME</span></div><div className="feature-copy"><p className="eyebrow orange">FROM THE COMMUNITY</p><div className="tag-row"><span>Arcade</span><span>Survival</span></div><h2 id="feature-title">Survive the void.<br/>Build your way out.</h2><p>Draft weapons, evolve your build, and face the Void Warden in <strong>Universe Eater: Ascension</strong>. Play on desktop or mobile.</p><div className="dialog-actions"><a className="primary-button" href="https://blaksmatic.github.io/universe-eater/" target="_blank" rel="noopener noreferrer">Play game <ArrowUpRight size={17}/></a><button className="secondary-button" onClick={()=>openGame(games[0])}>Details & updates</button></div><span className="feature-footnote">A game that keeps getting better.</span></div></section>
 <section className="catalogue" aria-labelledby="catalogue-title"><div className="catalogue-heading"><h2 id="catalogue-title">Find your next little obsession<span>{String(games.length).padStart(2,'0')}</span></h2><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search games, genres…" aria-label="Search games"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search">×</button>}</label></div><Tabs value={category} onValueChange={v=>setCategory(String(v))}><div className="filter-row"><TabsList aria-label="Game category" className="category-tabs">{categories.map(t=><TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList><span className="sort-label">Recently updated <ArrowDown size={14}/></span></div>{categories.map(t=><TabsContent key={t} value={t}><div className="games-grid">{filtered.map(game=><article key={game.id} className="game-card"><button className={`card-cover ${game.art}`} onClick={()=>openGame(game)} aria-label={`View ${game.title}`}>{game.image?<img src={game.image} alt={game.title+' cover'}/>:game.art==='universe'?<div className="universe-wordmark small-mark"><span>SURVIVE. EVOLVE. ASCEND.</span><strong>UNIVERSE<br/>EATER</strong><span>ASCENSION</span></div>:game.art==='orbit'?<img src="/images/orbit.png" alt="Little Orbit concept artwork"/>:<div className="type-cover"><span>{game.art==='tempo'?'JUST ONE':'THINK IN'}</span><strong>{game.art==='tempo'?'MORE.':'LOOPS'}</strong><span>{game.art==='tempo'?'A SMALL ARCADE OBSESSION':'A QUIET LITTLE PUZZLE'}</span></div>}<span className="cover-arrow"><ArrowUpRight size={19}/></span></button><div className="card-body"><div className="card-title"><button onClick={()=>openGame(game)}>{game.title}</button><span>FREE</span></div><p>{game.description}</p><div className="card-meta"><span><Sparkles size={13}/>{game.model}</span><span>{game.tags[0]}</span></div><div className="card-bottom"><span>by {game.creator}</span><button onClick={()=>openGame(game)} aria-label={`Leave feedback on ${game.title}`}><MessageSquare size={15}/> Feedback</button></div></div></article>)}</div>{!filtered.length&&<div className="empty-state"><Search size={28}/><h3>No games found</h3><p>Try another search or explore all games.</p><button className="secondary-button" onClick={()=>{setQuery('');setCategory('All games');}}>Clear filters</button></div>}</TabsContent>)}</Tabs></section>
 <section className="creator-strip"><span className="creator-icon"><Code2 size={27}/></span><div><h2>Made a little something?</h2><p>Host your game. Submit its page through a GitHub pull request. Keep improving it.</p></div><button className="secondary-button" onClick={()=>setSubmitOpen(true)}>Submit via GitHub <ArrowUpRight size={16}/></button></section>
</main>
 <footer><a className="brand small" href="/"><Flame size={18}/>SourceHearth</a><span>Free games. Open source. Human curiosity.</span><span className="footer-status"><span/> A community in the making</span></footer>
 <Dialog open={selected!==null} onOpenChange={open=>{if(!open&&!sending){setSelected(null);setFeedback('');setName('');setStatus('');}}}><DialogContent className="game-dialog sm:max-w-xl"><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.description}</DialogDescription>{selected&&<><div className="tag-row">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><p className="game-byline">By {selected.creator} · <a href={selected.repoUrl} target="_blank" rel="noopener noreferrer">View source ↗</a></p><div className="dialog-actions">{selected.playUrl?<a className="primary-button" href={selected.playUrl} target="_blank" rel="noopener noreferrer">Play game <ArrowUpRight size={16}/></a>:<button className="primary-button" disabled>Play · Coming with real listings</button>}{selected.repoUrl&&<a className="secondary-button" href={selected.repoUrl} target="_blank" rel="noopener noreferrer">View source <Code2 size={16}/></a>}</div><GameChangelog releases={selected.releases}/><form onSubmit={sendFeedback} className="feedback-form"><h3>Leave some feedback</h3><p>What was fun? Where did you get stuck? What would make you play again? Feedback is saved privately for review.</p><label>Your name <span>(optional)</span><input value={name} onChange={e=>setName(e.target.value)} maxLength={60} autoComplete="nickname" placeholder="Anonymous" disabled={sending}/></label><label>Your feedback<textarea value={feedback} onChange={e=>setFeedback(e.target.value)} required minLength={3} maxLength={2000} rows={4} placeholder="What caught your eye? What could be better?" disabled={sending}/></label><div className="form-bottom"><span>{feedback.length}/2000</span><button className="primary-button" disabled={sending||feedback.trim().length<3}>{sending?'Sending…':'Send feedback'} <ArrowUpRight size={15}/></button></div><p role="status" className="feedback-status">{status}</p></form></>}</DialogContent></Dialog>
 <Dialog open={submitOpen} onOpenChange={setSubmitOpen}><DialogContent className="game-dialog sm:max-w-lg"><DialogTitle>Submit your game via GitHub</DialogTitle><DialogDescription>Host your own game, then open a pull request to add its page to SourceHearth.</DialogDescription><ol className="submission-steps"><li><strong>Host your own game</strong><p>Publish a playable build on your own site or a game hosting service. Include the direct play URL.</p></li><li><strong>Add your game page</strong><p>Fork the SourceHearth repository and add a JSON page in games/: title, creator, description, screenshot, play URL, source URL, and AI tools. Include a version, release timestamp, and changelog.</p></li><li><strong>Open a pull request</strong><p>Submit your changes to SourceHearth for review. For future updates, open another pull request with your new version and release notes.</p></li></ol><p className="submission-future">Everything runs through GitHub for now. A simpler submission tool will come later.</p><a className="primary-button" href="https://github.com/blaksmatic/sourcehearth/fork" target="_blank" rel="noopener noreferrer">Fork & submit a pull request <ArrowUpRight size={16}/></a><a className="submission-guide" href="https://github.com/blaksmatic/sourcehearth/blob/main/CONTRIBUTING.md" target="_blank" rel="noopener noreferrer">Read the submission guide ↗</a></DialogContent></Dialog>
 </div>;
}


